/* Lossless gzip payloads generated by render_pages.py; no network dependencies. */
(() => {
  "use strict";
  async function decodeGzip(bytes) {
    if (typeof window.DecompressionStream === "function") {
      try {
        const stream = new Blob([bytes]).stream().pipeThrough(new window.DecompressionStream("gzip"));
        return await new Response(stream).text();
      } catch (_) { /* The pinned decoder also covers unavailable or broken native support. */ }
    }
    return new TextDecoder("utf-8", {fatal: true}).decode(window.fflate.gunzipSync(bytes));
  }
  async function loadJSON(path) {
    const response = await fetch(path);
    if (!response.ok) throw new Error("Data request failed: " + response.status);
    if (!path.endsWith(".gz")) return response.json();
    return JSON.parse(await decodeGzip(new Uint8Array(await response.arrayBuffer())));
  }
  window.TaxonMechData = {decodeGzip, loadJSON};
  for (const container of document.querySelectorAll("[data-gzip-content]")) {
    const bytes = Uint8Array.from(atob(container.dataset.gzipContent), char => char.charCodeAt(0));
    decodeGzip(bytes).then(html => {
      // This is the same autoescaped HTML emitted inline for smaller tables.
      // Only the encoding changes; source values never become executable HTML.
      const template = document.createElement("template");
      template.innerHTML = html;
      container.replaceChildren(template.content);
      delete container.dataset.gzipContent;
      if (window.location.hash) {
        let anchor = window.location.hash.slice(1);
        try { anchor = decodeURIComponent(anchor); } catch (_) { /* Keep the literal anchor. */ }
        document.getElementById(anchor)?.scrollIntoView();
      }
    }).catch(() => {
      container.querySelector('[role="status"]').textContent =
        "Could not display the strain table. Use the source YAML link below.";
    });
  }
})();
