#!/usr/bin/env python3
"""Keep README.md's "Current corpus" block in step with the corpus.

    python scripts/check_docs.py --write   # regenerate the block
    python scripts/check_docs.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from corpus import REPO_ROOT, load_records  # noqa: E402

from taxonmech.report import summarize  # noqa: E402

README = REPO_ROOT / "README.md"
BEGIN = "<!-- BEGIN GENERATED CORPUS STATS -->"
END = "<!-- END GENERATED CORPUS STATS -->"


def render_block() -> str:
    s = summarize(load_records())
    lines = [
        BEGIN,
        "<!-- Generated by scripts/check_docs.py; do not edit this block by hand. -->",
        f"**{s['total']:,} taxon records** are currently committed.",
        "",
        "| Domain | Records | | Rank | Records | | Attested by | Records |",
        "|---|---:|---|---|---:|---|---|---:|",
    ]
    domains = list(s["by_domain"].items())
    ranks = list(s["by_rank"].items())
    sources = list(s["by_source"].items())
    for i in range(max(len(domains), len(ranks), len(sources))):
        d = domains[i] if i < len(domains) else ("", "")
        r = ranks[i] if i < len(ranks) else ("", "")
        c = sources[i] if i < len(sources) else ("", "")
        lines.append(f"| {d[0]} | {d[1]} | | {r[0]} | {r[1]} | | {c[0]} | {c[1]} |")
    lines += [
        "",
        f"{s['strain_total']:,} BacDive strains are classified under these taxa "
        f"({s['strains_listed']:,} listed in records; {s['records_with_capped_listing']} records cap their "
        f"listing). {s['with_type_strain']} records list a type strain, "
        f"{s['with_correct_name']} carry an LPSN correct name, {s['with_gtdb']} map to GTDB "
        f"({s['genomes']:,} genomes), and {s['with_graphs']} carry causal graphs "
        f"({s['edges']} evidence-backed edges).",
        "",
        f"**{s['by_status'].get('REVIEWED', 0)} records are `REVIEWED`;** the remaining "
        f"{s['total'] - s['by_status'].get('REVIEWED', 0)} are `SEEDED` or `PROPOSED`.",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        print(f"README.md has no {BEGIN} ... {END} block", file=sys.stderr)
        return 1
    new_text = pattern.sub(lambda _m: render_block(), text)
    if args.write:
        README.write_text(new_text, encoding="utf-8")
        print("README.md corpus block refreshed")
        return 0
    if new_text != text:
        print("README.md corpus block is stale; run `just docs-stats`", file=sys.stderr)
        return 1
    print("README.md corpus block is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
